44

diff --git a/codereview.yml b/codereview.yml
--- a/codereview.yml
+++ b/codereview.yml
@@ -27,5 +27,27 @@ phases:
   build:
     commands:
       - echo $sonar_token $sonar_host_url $Project $Organization
-      - chmod +x codereview.sh
-      - source ./codereview.sh $sonar_token $sonar_host_url $Project $Organization
+      - result=`sonar-scanner -Dsonar.login=$sonar_token -Dsonar.host.url=$sonar_host_url -Dsonar.projectKey=$Project -Dsonar.organization=$Organization  -Dsonar.password=`
+      - sonar_task_id=$(echo $result | egrep -o "task\?id=[^ ]+" | cut -d'=' -f2)
+      -| # Allow time for SonarQube Background Task to complete
+        stat="PENDING";
+        while [ "$stat" != "SUCCESS" ]; do
+          if [ $stat = "FAILED" ] || [ $stat = "CANCELLED" ]; then
+            echo "SonarCloud task $sonar_task_id failed";
+            exit 1;
+          fi
+          stat=$(curl -u $sonar_token:"" $sonar_host_url/api/ce/task\?id=$sonar_task_id | jq -r '.task.status');
+          echo "SonarQube analysis status is $stat";
+          sleep 5;
+        done
+      sonar_analysis_id=$(curl -u $sonar_token:"" $sonar_host_url/api/ce/task\?id=$sonar_task_id | jq -r '.task.analysisId')
+      quality_status=$(curl -u $sonar_token:"" $sonar_host_url/api/qualitygates/project_status\?analysisId=$sonar_analysis_id | jq -r '.projectStatus.status')
+        if [ $quality_status = "ERROR" ]; then
+          content=$(echo "SonarQube analysis complete. Quality Gate Failed.\n\nTo see why, $sonar_link");
+          $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;
+        elif [ $quality_status = "OK" ]; then
+          content=$(echo "SonarQube analysis complete. Quality Gate Passed.\n\nFor details, $sonar_link");
+          #aws codecommit update-pull-request-approval-state --pull-request-id $PULL_REQUEST_ID --approval-state APPROVE --revision-id $REVISION_ID;
+        else
+          content="An unexpected error occurred while attempting to analyze with SonarQube.";
+        fi
